# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3568d35c62ab46e885462241f8c1fe61d79848109c25591af799337a20c89c7cd0c279558d0efb4f830ff5175918ebfa508dba3217aa693aad2b6a9ca9133251

test:
  secret_key_base: 537781f7368351f7a96cafe2e2aa3155143aca3431bd9e479a45a8334d4c8d5396c6788ba84860030ceafb9d96cc5f83ab9d164e75bbe14d92ddbfca2fe95baf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
